image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 5000
    onOpen: open-browser
    visibility: public
  - port: 9222
    onOpen: ignore
    visibility: private

tasks:
  - name: Setup & Install
    init: |
      npm install
      npm run build
    command: |
      echo "Extension ready for development!"
      npm run dev

  - name: Chrome Extension Preview
    command: |
      gp await-port 5000
      npm run preview

  - name: Test Runner
    command: |
      npm run test:watch

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-vscode.vscode-typescript-next
    - bradlc.vscode-tailwindcss
    - christian-kohler.path-intellisense